### ISSUE TITLE
Fails to compile with GCC trunk

### ISSUE THREAD

**Issue by le-migou** [boost-experimental/ut#292]
In case you're interested in upcoming versions of GCC, ut fails to compile with g++ (GCC) 10.0.0 20200108 (experimental)

    $ g++ -std=c++2a -Wall -Wextra -I../../external/boost_experimental/ut/include   -c -o tests.o tests.cpp
    In file included from tests.cpp:5:
    ../../external/boost_experimental/ut/include/boost/ut.hpp: In instantiation of ‘constexpr boost::ut::v1_1_6::detail::neq_<TLhs, TRhs>::neq_(const TLhs&, const TRhs&) [with TLhs = std::basic_string_view<char>; TRhs = std::basic_string_view<char>]’:
    ../../external/boost_experimental/ut/include/boost/ut.hpp:1747:31:   required from here
    ../../external/boost_experimental/ut/include/boost/ut.hpp:614:30: error: return type of ‘constexpr auto boost::ut::v1_1_6::operators::operator==(std::string_view, std::string_view)’ is not ‘bool’
      614 |             return get(lhs_) != get(rhs_);
          |                    ~~~~~~~~~~^~~~~~~~~~~~
    ../../external/boost_experimental/ut/include/boost/ut.hpp:614:30: note: used as rewritten candidate for comparison of ‘std::basic_string_view<char>’ and ‘std::basic_string_view<char>’
    ../../external/boost_experimental/ut/include/boost/ut.hpp:616:12: error: cannot convert ‘<brace-enclosed initializer list>’ to ‘const bool’ in initialization
      616 |         }()} {}
          |            ^
    make: *** [<builtin>: tests.o] Error 1

At first glance I'd say that the call to `operator!=(std::string_view, std::string_view)` in `neq_` uses the overload of `operator==(std::string_view, std::string_view` defined just above, which of course doesn't return a `bool`. Adding a `using std::operator==` solves the issue.

Now as to why GCC 9 doesn't complain, I have no idea.

**Comment by tambry** [comment]
Also seeing this issue. Prevents me from moving to GCC 10.
